# Generated by Django 2.1.1 on 2018-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ko', 'Korean'), ('ja', 'Japanese'), ('zhs', 'Chinese')], default='ko', max_length=10)),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('drawn_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
