# Generated by Django 2.1.1 on 2018-09-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
